spring.application.name=backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
frontend.url=${FRONTEND_URL}

judge0.url=${JUDGE0_URL}
judge0.api-key=${JUDGE0_API_KEY}
judge0.host=${JUDGE0_HOST}

email-verification.url=${EMAIL_VERIFICATION_URL}
email-verification.host=${EMAIL_VERIFICATION_HOST}
email-verification.api-key=${EMAIL_VERIFICATION_API_KEY}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoints.web.base-path=/actuator


server.port=8080
