spring.application.name=${SPRING_APPLICATION_NAME:backend}


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/CodeQuest}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:gKuLLai8T2OvsT9isj7n8OzO7EITEljXII3zL0l6QR8=}
jwt.expiration=${JWT_EXPIRATION:86400000}
frontend.url=${FRONTEND_URL:http://localhost:5173}